# Generated by Django 4.2 on 2026-02-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('type_absence', models.CharField(choices=[('CONGE', 'Congé'), ('FORMATION', 'Formation'), ('MALADIE', 'Maladie'), ('AUTRE', 'Autre')], max_length=10)),
                ('motif', models.TextField(blank=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='appointments.medecin', verbose_name='Médecin')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='PlageHoraire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('actif', models.BooleanField(default=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plages_horaires', to='appointments.medecin', verbose_name='Médecin')),
            ],
            options={
                'verbose_name': 'Plage horaire',
                'verbose_name_plural': 'Plages horaires',
                'ordering': ['jour_semaine', 'heure_debut'],
                'unique_together': {('medecin', 'jour_semaine', 'heure_debut')},
            },
        ),
    ]
