# Generated by Django 4.2 on 2026-02-05 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=20, unique=True, verbose_name='Numéro de facture')),
                ('date_emission', models.DateField(auto_now_add=True, verbose_name="Date d'émission")),
                ('date_echeance', models.DateField(verbose_name="Date d'échéance")),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('PARTIELLE', 'Paiement partiel'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=10)),
                ('montant_ht', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Montant HT')),
                ('tva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='TVA (%)')),
                ('montant_ttc', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Montant TTC')),
                ('montant_paye', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Montant payé')),
                ('notes', models.TextField(blank=True)),
                ('consultation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.consultationmedicale')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-date_emission'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('montant', models.DecimalField(decimal_places=3, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CHEQUE', 'Chèque'), ('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement')], max_length=10)),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='billing.facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=200, verbose_name='Désignation')),
                ('quantite', models.IntegerField(default=1, verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Prix unitaire')),
                ('montant_total', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Montant total')),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='billing.facture')),
            ],
        ),
    ]
