# Generated by Django 4.2 on 2026-02-05 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(choices=[('GEN', 'Médecine générale'), ('CARD', 'Cardiologie'), ('DERM', 'Dermatologie'), ('PED', 'Pédiatrie'), ('ORT', 'Orthopédie'), ('OPH', 'Ophtalmologie'), ('GYN', 'Gynécologie'), ('NEUR', 'Neurologie'), ('PSY', 'Psychiatrie')], max_length=4, verbose_name='Spécialité')),
                ('numero_ordre', models.CharField(max_length=50, unique=True, verbose_name="Numéro d'ordre")),
                ('telephone_cabinet', models.CharField(max_length=20, verbose_name='Téléphone cabinet')),
                ('bio', models.TextField(blank=True, verbose_name='Biographie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médecin',
                'verbose_name_plural': 'Médecins',
            },
        ),
        migrations.CreateModel(
            name='RendezVous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(verbose_name='Date et heure')),
                ('duree_minutes', models.IntegerField(default=30, verbose_name='Durée (minutes)')),
                ('motif', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Terminé')], default='ATTENTE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='appointments.medecin', verbose_name='Médecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['date_heure'],
                'unique_together': {('medecin', 'date_heure')},
            },
        ),
    ]
